# Generated by Django 5.0.3 on 2024-11-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boton',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
