# Generated by Django 5.0.3 on 2024-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_boton_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='boton',
            name='imgBoton',
            field=models.CharField(default='', max_length=50),
        ),
    ]
