# Generated by Django 5.0.3 on 2024-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_boton_imgboton'),
    ]

    operations = [
        migrations.AddField(
            model_name='boton',
            name='mensaje',
            field=models.CharField(default='', max_length=50),
        ),
    ]
